import type { ISODateTime, UUID } from './common';

export type ActType = 'dj' | 'live_band';

export interface DjProfile {
  id: UUID;
  name: string;
  type: ActType;
  genres: string[];
  avatarUrl?: string;
  bio?: string;
  instagramHandle?: string;
  autoGenerated: boolean;
  claimedByUserId?: UUID;
  averageRating?: number;
  followerCount: number;
  createdAt: ISODateTime;
}

export interface DjEvent {
  id: UUID;
  djId: UUID;
  venueId: UUID;
  eventName?: string;
  startsAt: ISODateTime;
  endsAt?: ISODateTime;
}

export interface DjRating {
  id: UUID;
  djId: UUID;
  userId: UUID;
  eventId: UUID;
  vibe: number;
  musicQuality: number;
  crowdEnergy: number;
  createdAt: ISODateTime;
}
