import { PrismaClient } from '../src/prisma/generated';

const prisma = new PrismaClient();

const venues = [
  // ── Malaysia — Kuala Lumpur ──
  {
    name: 'Zouk KL',
    slug: 'zouk-kl',
    category: 'club',
    description: 'Iconic superclub spanning multiple rooms with world-class DJs and immersive production.',
    area: 'trec',
    country: 'MY',
    address: 'TREC, 436 Jalan Tun Razak, 50400 Kuala Lumpur',
    lat: 3.1555,
    lng: 101.7163,
    instagramHandle: 'zoukkl',
    barClosesAt: '03:00',
    priceRange: 3,
    crowdCapacity: 1500,
    googleRating: 4.0,
    vibeTags: ['energetic', 'premium', 'late-night'],
    genreTags: ['EDM', 'house', 'hip-hop'],
  },
  {
    name: 'Heli Lounge Bar',
    slug: 'heli-lounge-bar',
    category: 'rooftop',
    description: 'Open-air rooftop bar on a helipad with panoramic KL skyline views.',
    area: 'bukit_bintang',
    country: 'MY',
    address: '34th Floor, Menara KH, Jalan Sultan Ismail, 50250 KL',
    lat: 3.1490,
    lng: 101.7100,
    instagramHandle: 'heliloungebar',
    barClosesAt: '01:00',
    priceRange: 3,
    crowdCapacity: 200,
    googleRating: 4.2,
    vibeTags: ['scenic', 'chill', 'instagrammable'],
    genreTags: ['lounge', 'deep house'],
  },
  {
    name: 'PS150',
    slug: 'ps150',
    category: 'speakeasy',
    description: 'Award-winning speakeasy hidden behind a toy shop facade in Chinatown.',
    area: 'chinatown',
    country: 'MY',
    address: '150 Jalan Petaling, 50000 Kuala Lumpur',
    lat: 3.1438,
    lng: 101.6960,
    instagramHandle: 'ps150bar',
    barClosesAt: '01:00',
    priceRange: 3,
    crowdCapacity: 80,
    googleRating: 4.5,
    vibeTags: ['intimate', 'craft-cocktails', 'hidden'],
    genreTags: ['jazz', 'ambient'],
  },
  {
    name: 'Coley Cocktail Bar',
    slug: 'coley-cocktail-bar',
    category: 'bar',
    description: 'Top-ranked cocktail bar known for creative Malaysian-inspired drinks.',
    area: 'bangsar',
    country: 'MY',
    address: '6, Jalan Kemuja, Bangsar, 59000 KL',
    lat: 3.1300,
    lng: 101.6715,
    instagramHandle: 'coleycocktailbar',
    barClosesAt: '00:00',
    priceRange: 3,
    crowdCapacity: 60,
    googleRating: 4.6,
    vibeTags: ['craft-cocktails', 'cozy', 'date-night'],
    genreTags: ['jazz', 'soul'],
  },
  {
    name: 'Havana Bar & Grill',
    slug: 'havana-bar-grill',
    category: 'bar',
    description: 'Lively Latin-themed bar on Changkat with live music and mojitos.',
    area: 'changkat',
    country: 'MY',
    address: '2 Changkat Bukit Bintang, 50200 KL',
    lat: 3.1465,
    lng: 101.7095,
    instagramHandle: 'havanamalaysia',
    barClosesAt: '02:00',
    priceRange: 2,
    crowdCapacity: 120,
    googleRating: 4.1,
    vibeTags: ['lively', 'latin', 'live-music'],
    genreTags: ['latin', 'reggaeton', 'salsa'],
  },
  {
    name: 'Elysium KL',
    slug: 'elysium-kl',
    category: 'club',
    description: 'Premium nightclub in TREC with themed rooms and international DJ lineups.',
    area: 'trec',
    country: 'MY',
    address: 'TREC, 438 Jalan Tun Razak, 50400 KL',
    lat: 3.1557,
    lng: 101.7165,
    instagramHandle: 'elysiumkl',
    barClosesAt: '03:00',
    priceRange: 4,
    crowdCapacity: 800,
    googleRating: 3.8,
    vibeTags: ['vip', 'premium', 'bottle-service'],
    genreTags: ['EDM', 'techno', 'commercial'],
  },
  {
    name: 'View Rooftop Bar',
    slug: 'view-rooftop-bar',
    category: 'rooftop',
    description: 'Stylish rooftop with infinity pool views overlooking the Petronas Towers.',
    area: 'klcc',
    country: 'MY',
    address: 'Level 39, GTower, Jalan Tun Razak, 50400 KL',
    lat: 3.1580,
    lng: 101.7210,
    instagramHandle: 'viewrooftopbar',
    barClosesAt: '01:00',
    priceRange: 4,
    crowdCapacity: 150,
    googleRating: 4.3,
    vibeTags: ['skyline', 'premium', 'sunset'],
    genreTags: ['lounge', 'house'],
  },
  {
    name: 'The Whisky Bar',
    slug: 'the-whisky-bar',
    category: 'bar',
    description: 'Cozy whisky-focused bar in Changkat with over 300 labels.',
    area: 'changkat',
    country: 'MY',
    address: '46 Changkat Bukit Bintang, 50200 KL',
    lat: 3.1470,
    lng: 101.7098,
    instagramHandle: 'thewhiskybar_kl',
    barClosesAt: '01:00',
    priceRange: 3,
    crowdCapacity: 50,
    googleRating: 4.4,
    vibeTags: ['intimate', 'whisky', 'sophisticated'],
    genreTags: ['jazz', 'blues'],
  },
  {
    name: 'Jungle Bird',
    slug: 'jungle-bird',
    category: 'bar',
    description: 'Tiki-inspired craft cocktail bar with tropical drinks and quirky decor.',
    area: 'damansara',
    country: 'MY',
    address: 'Plaza Damansara, Jalan Medan Setia 1, 50490 KL',
    lat: 3.1385,
    lng: 101.6580,
    instagramHandle: 'junglebirdkl',
    barClosesAt: '00:00',
    priceRange: 2,
    crowdCapacity: 45,
    googleRating: 4.5,
    vibeTags: ['tiki', 'creative', 'funky'],
    genreTags: ['reggae', 'funk'],
  },
  {
    name: 'Fuego at Troika',
    slug: 'fuego-at-troika',
    category: 'lounge',
    description: 'Upscale South American lounge with live DJs and stunning KLCC views.',
    area: 'klcc',
    country: 'MY',
    address: 'Level 23A, Tower B, The Troika, Persiaran KLCC, 50450 KL',
    lat: 3.1575,
    lng: 101.7195,
    instagramHandle: 'fuegokl',
    barClosesAt: '02:00',
    priceRange: 4,
    crowdCapacity: 200,
    googleRating: 4.2,
    vibeTags: ['upscale', 'views', 'latin'],
    genreTags: ['latin', 'house', 'commercial'],
  },
  {
    name: 'Bar Trigona',
    slug: 'bar-trigona',
    category: 'bar',
    description: 'Award-winning cocktail bar at Four Seasons KL using local Malaysian ingredients and trigona honey.',
    area: 'klcc',
    country: 'MY',
    address: 'Four Seasons Place, 145 Jalan Ampang, 50450 KL',
    lat: 3.1585,
    lng: 101.7230,
    instagramHandle: 'bartrigona',
    barClosesAt: '01:00',
    priceRange: 4,
    crowdCapacity: 65,
    googleRating: 4.6,
    vibeTags: ['craft-cocktails', 'premium', 'sophisticated'],
    genreTags: ['jazz', 'lounge'],
  },
  {
    name: 'Marini\'s on 57',
    slug: 'marinis-on-57',
    category: 'rooftop',
    description: 'Ultra-premium rooftop bar on the 57th floor of Petronas Tower 3 with direct twin tower views.',
    area: 'klcc',
    country: 'MY',
    address: 'Level 57, Menara 3 Petronas, Persiaran KLCC, 50088 KL',
    lat: 3.1580,
    lng: 101.7135,
    instagramHandle: 'marinison57',
    barClosesAt: '01:00',
    priceRange: 4,
    crowdCapacity: 120,
    googleRating: 4.3,
    vibeTags: ['skyline', 'luxury', 'instagrammable'],
    genreTags: ['lounge', 'deep house'],
  },
  {
    name: 'Troika Sky Dining',
    slug: 'troika-sky-dining',
    category: 'lounge',
    description: 'Fine dining and cocktail destination perched above KLCC with open-air terrace seating.',
    area: 'klcc',
    country: 'MY',
    address: 'Level 23, Tower B, The Troika, Persiaran KLCC, 50450 KL',
    lat: 3.1573,
    lng: 101.7192,
    instagramHandle: 'troikaskydining',
    barClosesAt: '00:00',
    priceRange: 4,
    crowdCapacity: 100,
    googleRating: 4.1,
    vibeTags: ['fine-dining', 'views', 'romantic'],
    genreTags: ['lounge', 'jazz'],
  },
  {
    name: 'SkyBar KL',
    slug: 'skybar-kl',
    category: 'rooftop',
    description: 'Iconic rooftop bar at Traders Hotel with unobstructed Petronas Towers views and poolside seating.',
    area: 'klcc',
    country: 'MY',
    address: 'Level 33, Traders Hotel, Jalan Pinang, 50450 KL',
    lat: 3.1565,
    lng: 101.7175,
    instagramHandle: 'skybarkl',
    barClosesAt: '01:00',
    priceRange: 3,
    crowdCapacity: 180,
    googleRating: 4.2,
    vibeTags: ['skyline', 'pool', 'sunset'],
    genreTags: ['house', 'commercial'],
  },
  {
    name: 'Birch KL',
    slug: 'birch-kl',
    category: 'bar',
    description: 'Minimalist cocktail bar in Bangsar with a concise rotating menu and local spirit focus.',
    area: 'bangsar',
    country: 'MY',
    address: '8 Jalan Kemuja, Bangsar, 59000 KL',
    lat: 3.1303,
    lng: 101.6718,
    instagramHandle: 'birchkl',
    barClosesAt: '00:00',
    priceRange: 3,
    crowdCapacity: 40,
    googleRating: 4.5,
    vibeTags: ['minimalist', 'craft-cocktails', 'intimate'],
    genreTags: ['ambient', 'soul'],
  },
  {
    name: 'Mantra Bar KL',
    slug: 'mantra-bar-kl',
    category: 'bar',
    description: 'Bangsar neighbourhood bar with creative cocktails and a relaxed vinyl-soundtrack atmosphere.',
    area: 'bangsar',
    country: 'MY',
    address: '30 Jalan Telawi 2, Bangsar, 59100 KL',
    lat: 3.1310,
    lng: 101.6700,
    instagramHandle: 'mantrabarkl',
    barClosesAt: '01:00',
    priceRange: 2,
    crowdCapacity: 55,
    googleRating: 4.3,
    vibeTags: ['relaxed', 'vinyl', 'neighbourhood'],
    genreTags: ['funk', 'soul', 'jazz'],
  },
  {
    name: 'Skullduggery',
    slug: 'skullduggery-bangsar',
    category: 'speakeasy',
    description: 'Gothic-themed speakeasy tucked behind a bookshelf entrance with theatrical cocktails.',
    area: 'bangsar',
    country: 'MY',
    address: '19 Jalan Telawi 3, Bangsar, 59100 KL',
    lat: 3.1295,
    lng: 101.6710,
    instagramHandle: 'skullduggerykl',
    barClosesAt: '01:00',
    priceRange: 3,
    crowdCapacity: 50,
    googleRating: 4.4,
    vibeTags: ['hidden', 'theatrical', 'dark'],
    genreTags: ['ambient', 'trip-hop'],
  },
  {
    name: 'The Deceased',
    slug: 'the-deceased',
    category: 'speakeasy',
    description: 'Funeral-themed speakeasy in a heritage shophouse with coffin seating and macabre cocktails.',
    area: 'chinatown',
    country: 'MY',
    address: '118 Jalan Petaling, 50000 Kuala Lumpur',
    lat: 3.1435,
    lng: 101.6955,
    instagramHandle: 'thedeceasedkl',
    barClosesAt: '01:00',
    priceRange: 3,
    crowdCapacity: 45,
    googleRating: 4.3,
    vibeTags: ['quirky', 'hidden', 'themed'],
    genreTags: ['jazz', 'ambient'],
  },
  {
    name: 'JungleBird Chinatown',
    slug: 'junglebird-chinatown',
    category: 'bar',
    description: 'Second outpost of the popular tiki bar nestled among Chinatown heritage shophouses.',
    area: 'chinatown',
    country: 'MY',
    address: '174 Jalan Petaling, 50000 Kuala Lumpur',
    lat: 3.1442,
    lng: 101.6968,
    instagramHandle: 'junglebirdchinatown',
    barClosesAt: '00:00',
    priceRange: 2,
    crowdCapacity: 50,
    googleRating: 4.4,
    vibeTags: ['tiki', 'heritage', 'funky'],
    genreTags: ['reggae', 'funk'],
  },
  {
    name: 'KYO KL',
    slug: 'kyo-kl',
    category: 'club',
    description: 'Japanese-inspired nightclub with resident DJs, bottle service, and sleek interiors.',
    area: 'bukit_bintang',
    country: 'MY',
    address: 'Mandarin Oriental, Jalan Pinang, 50088 KL',
    lat: 3.1530,
    lng: 101.7140,
    instagramHandle: 'kyokl',
    barClosesAt: '03:00',
    priceRange: 4,
    crowdCapacity: 600,
    googleRating: 3.7,
    vibeTags: ['premium', 'bottle-service', 'late-night'],
    genreTags: ['hip-hop', 'commercial', 'EDM'],
  },
  {
    name: 'Suzie Wong KL',
    slug: 'suzie-wong-kl',
    category: 'club',
    description: 'Multi-level nightclub and live music venue at TREC with diverse party nights.',
    area: 'trec',
    country: 'MY',
    address: 'TREC, 434 Jalan Tun Razak, 50400 KL',
    lat: 3.1553,
    lng: 101.7160,
    instagramHandle: 'suziewongkl',
    barClosesAt: '03:00',
    priceRange: 2,
    crowdCapacity: 500,
    googleRating: 3.9,
    vibeTags: ['lively', 'diverse', 'late-night'],
    genreTags: ['commercial', 'hip-hop', 'EDM'],
  },
  {
    name: 'Iron Fairies',
    slug: 'iron-fairies-kl',
    category: 'bar',
    description: 'Whimsical steampunk bar hidden in TREC with hand-crafted iron fairy figurines and jazz.',
    area: 'trec',
    country: 'MY',
    address: 'TREC, 434 Jalan Tun Razak, 50400 KL',
    lat: 3.1554,
    lng: 101.7162,
    instagramHandle: 'ironfairieskl',
    barClosesAt: '01:00',
    priceRange: 3,
    crowdCapacity: 70,
    googleRating: 4.2,
    vibeTags: ['whimsical', 'steampunk', 'hidden'],
    genreTags: ['jazz', 'blues'],
  },
  {
    name: 'Pahit',
    slug: 'pahit-kl',
    category: 'bar',
    description: 'Colonial-inspired gin bar in Chinatown with Southeast Asian botanicals and heritage charm.',
    area: 'chinatown',
    country: 'MY',
    address: '3 Jalan Sin Chew Kee, 50000 Kuala Lumpur',
    lat: 3.1430,
    lng: 101.6978,
    instagramHandle: 'pahitkl',
    barClosesAt: '00:00',
    priceRange: 3,
    crowdCapacity: 40,
    googleRating: 4.5,
    vibeTags: ['colonial', 'craft-cocktails', 'heritage'],
    genreTags: ['jazz', 'lounge'],
  },
  {
    name: 'Ril\'s Bangsar',
    slug: 'rils-bangsar',
    category: 'bar',
    description: 'Neighbourhood gastro-bar in Bangsar serving craft beers and sharing plates late into the night.',
    area: 'bangsar',
    country: 'MY',
    address: '44 Jalan Telawi 5, Bangsar, 59100 KL',
    lat: 3.1308,
    lng: 101.6725,
    instagramHandle: 'rilsbangsar',
    barClosesAt: '01:00',
    priceRange: 2,
    crowdCapacity: 80,
    googleRating: 4.1,
    vibeTags: ['neighbourhood', 'casual', 'craft-beer'],
    genreTags: ['indie', 'pop'],
  },
  {
    name: 'Soma KL',
    slug: 'soma-kl',
    category: 'lounge',
    description: 'Hartamas lounge bar with a chill garden patio, cocktails, and weekend DJ sets.',
    area: 'hartamas',
    country: 'MY',
    address: '22 Jalan Sri Hartamas 7, 50480 KL',
    lat: 3.1660,
    lng: 101.6575,
    instagramHandle: 'somakl',
    barClosesAt: '01:00',
    priceRange: 2,
    crowdCapacity: 90,
    googleRating: 4.0,
    vibeTags: ['garden', 'chill', 'weekend'],
    genreTags: ['house', 'lounge'],
  },
  {
    name: 'The Good Batch',
    slug: 'the-good-batch-hartamas',
    category: 'bar',
    description: 'Craft cocktail and coffee bar in Sri Hartamas with exposed-brick interiors.',
    area: 'hartamas',
    country: 'MY',
    address: '10 Jalan Sri Hartamas 1, 50480 KL',
    lat: 3.1655,
    lng: 101.6568,
    instagramHandle: 'thegoodbatchkl',
    barClosesAt: '00:00',
    priceRange: 2,
    crowdCapacity: 45,
    googleRating: 4.3,
    vibeTags: ['cozy', 'craft-cocktails', 'casual'],
    genreTags: ['indie', 'acoustic'],
  },
  {
    name: 'The Roof',
    slug: 'the-roof-bandar-utama',
    category: 'rooftop',
    description: 'Massive rooftop entertainment complex in Bandar Utama with bars, restaurants, and live events.',
    area: 'damansara',
    country: 'MY',
    address: 'Level 1, First Avenue, Bandar Utama, 47800 PJ',
    lat: 3.1345,
    lng: 101.6155,
    instagramHandle: 'theroofmy',
    barClosesAt: '01:00',
    priceRange: 2,
    crowdCapacity: 400,
    googleRating: 3.9,
    vibeTags: ['lively', 'events', 'open-air'],
    genreTags: ['commercial', 'pop', 'EDM'],
  },
  {
    name: 'Wholly Spirits',
    slug: 'wholly-spirits',
    category: 'bar',
    description: 'Intimate whisky and craft spirits bar in Damansara with knowledgeable bartenders.',
    area: 'damansara',
    country: 'MY',
    address: '6 Jalan SS20/11, Damansara Kim, 47400 PJ',
    lat: 3.1260,
    lng: 101.6370,
    instagramHandle: 'whollyspirits',
    barClosesAt: '00:00',
    priceRange: 3,
    crowdCapacity: 35,
    googleRating: 4.6,
    vibeTags: ['intimate', 'whisky', 'craft-spirits'],
    genreTags: ['jazz', 'blues'],
  },
  {
    name: 'Apex Lounge',
    slug: 'apex-lounge-mont-kiara',
    category: 'lounge',
    description: 'Modern cocktail lounge in Mont Kiara popular with expats and late-night diners.',
    area: 'mont_kiara',
    country: 'MY',
    address: '163 Retail Park, Jalan Kiara, Mont Kiara, 50480 KL',
    lat: 3.1710,
    lng: 101.6510,
    instagramHandle: 'apexloungekl',
    barClosesAt: '01:00',
    priceRange: 3,
    crowdCapacity: 100,
    googleRating: 4.0,
    vibeTags: ['modern', 'expat-friendly', 'late-night'],
    genreTags: ['house', 'commercial'],
  },
  {
    name: 'The Locker & Loft',
    slug: 'the-locker-and-loft',
    category: 'speakeasy',
    description: 'Hidden cocktail den in Mont Kiara accessed through a locker door with prohibition-era vibes.',
    area: 'mont_kiara',
    country: 'MY',
    address: '11 Plaza Mont Kiara, 50480 KL',
    lat: 3.1720,
    lng: 101.6530,
    instagramHandle: 'lockerandloftkl',
    barClosesAt: '01:00',
    priceRange: 3,
    crowdCapacity: 50,
    googleRating: 4.2,
    vibeTags: ['hidden', 'prohibition', 'intimate'],
    genreTags: ['jazz', 'swing'],
  },
  {
    name: 'Mercat Barcelona Gastrobar',
    slug: 'mercat-changkat',
    category: 'bar',
    description: 'Spanish-inspired gastrobar on Changkat with tapas, sangria, and a vibrant terrace.',
    area: 'changkat',
    country: 'MY',
    address: '8 Changkat Bukit Bintang, 50200 KL',
    lat: 3.1468,
    lng: 101.7093,
    instagramHandle: 'mercatbcnkl',
    barClosesAt: '01:00',
    priceRange: 2,
    crowdCapacity: 100,
    googleRating: 4.1,
    vibeTags: ['terrace', 'lively', 'tapas'],
    genreTags: ['latin', 'pop'],
  },
  {
    name: 'Nagaba',
    slug: 'nagaba-bukit-bintang',
    category: 'bar',
    description: 'Moody cocktail bar in Bukit Bintang combining Japanese precision with Malaysian ingredients.',
    area: 'bukit_bintang',
    country: 'MY',
    address: 'Lot 185, Jalan Bukit Bintang, 55100 KL',
    lat: 3.1485,
    lng: 101.7115,
    instagramHandle: 'nagababar',
    barClosesAt: '00:00',
    priceRange: 3,
    crowdCapacity: 40,
    googleRating: 4.4,
    vibeTags: ['moody', 'craft-cocktails', 'japanese'],
    genreTags: ['ambient', 'lounge'],
  },
  {
    name: 'Three X Co',
    slug: 'three-x-co',
    category: 'live_music',
    description: 'Live music venue and bar on Changkat hosting nightly local and touring bands.',
    area: 'changkat',
    country: 'MY',
    address: '30 Changkat Bukit Bintang, 50200 KL',
    lat: 3.1472,
    lng: 101.7100,
    instagramHandle: 'threexco',
    barClosesAt: '02:00',
    priceRange: 2,
    crowdCapacity: 150,
    googleRating: 4.0,
    vibeTags: ['live-music', 'lively', 'local'],
    genreTags: ['rock', 'blues', 'covers'],
  },
  {
    name: 'Rabbit Hole',
    slug: 'rabbit-hole-changkat',
    category: 'bar',
    description: 'Quirky multi-level bar on Changkat with themed rooms and eclectic cocktail menu.',
    area: 'changkat',
    country: 'MY',
    address: '18 Changkat Bukit Bintang, 50200 KL',
    lat: 3.1467,
    lng: 101.7092,
    instagramHandle: 'rabbitholekl',
    barClosesAt: '02:00',
    priceRange: 2,
    crowdCapacity: 110,
    googleRating: 4.0,
    vibeTags: ['quirky', 'themed', 'eclectic'],
    genreTags: ['pop', 'commercial', 'indie'],
  },
  {
    name: 'Coppersmith',
    slug: 'coppersmith-kl',
    category: 'bar',
    description: 'Rustic-industrial gastropub in TTDI serving craft brews, smoked meats, and weekend live acts.',
    area: 'damansara',
    country: 'MY',
    address: '17 Jalan Tun Mohd Fuad, TTDI, 60000 KL',
    lat: 3.1355,
    lng: 101.6315,
    instagramHandle: 'coppersmithkl',
    barClosesAt: '01:00',
    priceRange: 2,
    crowdCapacity: 100,
    googleRating: 4.1,
    vibeTags: ['rustic', 'craft-beer', 'live-music'],
    genreTags: ['rock', 'acoustic', 'indie'],
  },

  // ── Sri Lanka — Colombo ──
  {
    name: 'Sky Lounge Colombo',
    slug: 'sky-lounge-colombo',
    category: 'rooftop',
    description: 'Colombo\'s premier rooftop bar atop Kingsbury Hotel with ocean views.',
    area: 'fort',
    country: 'LK',
    address: 'The Kingsbury, 48 Janadhipathi Mawatha, Colombo 01',
    lat: 6.9344,
    lng: 79.8428,
    instagramHandle: 'kingsburycolombo',
    barClosesAt: '01:00',
    priceRange: 4,
    crowdCapacity: 120,
    googleRating: 4.1,
    vibeTags: ['ocean-view', 'premium', 'sunset'],
    genreTags: ['lounge', 'deep house'],
  },
  {
    name: 'ON14 Rooftop Bar',
    slug: 'on14-rooftop-bar',
    category: 'rooftop',
    description: 'Award-winning rooftop lounge on the 14th floor with craft cocktails and city panorama.',
    area: 'kollupitiya',
    country: 'LK',
    address: 'OZO Colombo, 36 Kollupitiya Rd, Colombo 03',
    lat: 6.9110,
    lng: 79.8498,
    instagramHandle: 'on14rooftop',
    barClosesAt: '00:00',
    priceRange: 3,
    crowdCapacity: 80,
    googleRating: 4.3,
    vibeTags: ['craft-cocktails', 'scenic', 'lounge'],
    genreTags: ['house', 'chill'],
  },
  {
    name: 'The Honey Beach Club',
    slug: 'the-honey-beach-club',
    category: 'club',
    description: 'Beachfront party venue in Mount Lavinia with weekend DJ nights and pool parties.',
    area: 'mount_lavinia',
    country: 'LK',
    address: 'Marine Drive, Mount Lavinia',
    lat: 6.8385,
    lng: 79.8645,
    instagramHandle: 'honeybeachclub',
    barClosesAt: '02:00',
    priceRange: 2,
    crowdCapacity: 300,
    googleRating: 3.9,
    vibeTags: ['beachfront', 'pool-party', 'weekend'],
    genreTags: ['EDM', 'commercial', 'reggaeton'],
  },
  {
    name: 'Rhythm & Blues',
    slug: 'rhythm-and-blues',
    category: 'bar',
    description: 'Colombo\'s go-to live music bar with nightly bands and a loyal crowd.',
    area: 'kollupitiya',
    country: 'LK',
    address: 'Daytona Bldg, 25 Chatham St, Colombo 03',
    lat: 6.9125,
    lng: 79.8510,
    instagramHandle: 'rnbcolombo',
    barClosesAt: '01:00',
    priceRange: 2,
    crowdCapacity: 100,
    googleRating: 4.2,
    vibeTags: ['live-music', 'lively', 'classic'],
    genreTags: ['rock', 'blues', 'covers'],
  },
  {
    name: 'Curve Bar',
    slug: 'curve-bar',
    category: 'lounge',
    description: 'Chic cocktail lounge inside Colombo Courtyard with art-deco interiors.',
    area: 'cinnamon_gardens',
    country: 'LK',
    address: '32 Alfred House Ave, Colombo 03',
    lat: 6.9065,
    lng: 79.8575,
    instagramHandle: 'curvebarcolombo',
    barClosesAt: '00:00',
    priceRange: 3,
    crowdCapacity: 60,
    googleRating: 4.0,
    vibeTags: ['chic', 'art-deco', 'date-night'],
    genreTags: ['lounge', 'jazz'],
  },
  {
    name: 'Cloud Red',
    slug: 'cloud-red-colombo',
    category: 'rooftop',
    description: 'Rooftop bar and lounge atop Cinnamon Red with a vibrant young crowd and city panorama.',
    area: 'kollupitiya',
    country: 'LK',
    address: 'Cinnamon Red, 59 Ananda Coomaraswamy Mawatha, Colombo 03',
    lat: 6.9095,
    lng: 79.8505,
    instagramHandle: 'cloudredcolombo',
    barClosesAt: '01:00',
    priceRange: 2,
    crowdCapacity: 150,
    googleRating: 4.0,
    vibeTags: ['rooftop', 'young-crowd', 'energetic'],
    genreTags: ['commercial', 'EDM'],
  },
  {
    name: 'Kaema Sutra',
    slug: 'kaema-sutra',
    category: 'lounge',
    description: 'Celebrity chef Dharshan Munidasa\'s stylish restaurant-lounge with creative Sri Lankan cocktails.',
    area: 'fort',
    country: 'LK',
    address: 'Shangri-La Colombo, 1 Galle Face, Colombo 02',
    lat: 6.9280,
    lng: 79.8440,
    instagramHandle: 'kaemasutra',
    barClosesAt: '00:00',
    priceRange: 4,
    crowdCapacity: 80,
    googleRating: 4.3,
    vibeTags: ['upscale', 'fusion', 'stylish'],
    genreTags: ['lounge', 'jazz'],
  },
  {
    name: 'Loft Lounge & Bar',
    slug: 'loft-lounge-colombo',
    category: 'lounge',
    description: 'Industrial-chic lounge in Bambalapitiya with craft cocktails and DJ nights on weekends.',
    area: 'bambalapitiya',
    country: 'LK',
    address: '15 Vajira Rd, Colombo 04',
    lat: 6.8920,
    lng: 79.8565,
    instagramHandle: 'loftloungecmb',
    barClosesAt: '01:00',
    priceRange: 2,
    crowdCapacity: 90,
    googleRating: 4.0,
    vibeTags: ['industrial', 'weekend', 'dj-nights'],
    genreTags: ['house', 'commercial'],
  },
  {
    name: 'Sugar Nightclub',
    slug: 'sugar-nightclub-colombo',
    category: 'club',
    description: 'Colombo\'s long-running nightclub at Taj Samudra with international and local DJs.',
    area: 'kollupitiya',
    country: 'LK',
    address: 'Taj Samudra, 25 Galle Face Centre Rd, Colombo 03',
    lat: 6.9145,
    lng: 79.8465,
    instagramHandle: 'sugarcolombo',
    barClosesAt: '03:00',
    priceRange: 3,
    crowdCapacity: 350,
    googleRating: 3.8,
    vibeTags: ['legendary', 'late-night', 'energetic'],
    genreTags: ['EDM', 'hip-hop', 'commercial'],
  },
  {
    name: 'Botanik Rooftop Bar',
    slug: 'botanik-rooftop',
    category: 'rooftop',
    description: 'Tropical rooftop bar with botanical cocktails and a living-wall garden atmosphere.',
    area: 'cinnamon_gardens',
    country: 'LK',
    address: '19 Alfred House Gardens, Colombo 03',
    lat: 6.9055,
    lng: 79.8560,
    instagramHandle: 'botanikcolombo',
    barClosesAt: '00:00',
    priceRange: 3,
    crowdCapacity: 70,
    googleRating: 4.2,
    vibeTags: ['botanical', 'tropical', 'scenic'],
    genreTags: ['lounge', 'chill'],
  },
  {
    name: 'H2O at Mount Lavinia Hotel',
    slug: 'h2o-mount-lavinia',
    category: 'bar',
    description: 'Beachfront bar at the historic Mount Lavinia Hotel with waves crashing right below.',
    area: 'mount_lavinia',
    country: 'LK',
    address: 'Mount Lavinia Hotel, 100 Hotel Rd, Mount Lavinia',
    lat: 6.8380,
    lng: 79.8650,
    instagramHandle: 'mountlaviniahotel',
    barClosesAt: '01:00',
    priceRange: 2,
    crowdCapacity: 120,
    googleRating: 4.1,
    vibeTags: ['beachfront', 'heritage', 'sunset'],
    genreTags: ['reggae', 'covers', 'chill'],
  },
  {
    name: 'The Keg',
    slug: 'the-keg-colombo',
    category: 'bar',
    description: 'Popular sports bar and pub in Bambalapitiya with draught beer and big-screen sports.',
    area: 'bambalapitiya',
    country: 'LK',
    address: '389 Galle Rd, Colombo 04',
    lat: 6.8905,
    lng: 79.8555,
    instagramHandle: 'thekegcolombo',
    barClosesAt: '01:00',
    priceRange: 1,
    crowdCapacity: 100,
    googleRating: 3.9,
    vibeTags: ['sports', 'casual', 'beer'],
    genreTags: ['pop', 'rock'],
  },
  {
    name: 'Kingsbury Poolside',
    slug: 'kingsbury-poolside',
    category: 'lounge',
    description: 'Poolside bar at Kingsbury Hotel with evening cocktail service and harbour views.',
    area: 'fort',
    country: 'LK',
    address: 'The Kingsbury, 48 Janadhipathi Mawatha, Colombo 01',
    lat: 6.9348,
    lng: 79.8432,
    instagramHandle: 'kingsburypoolside',
    barClosesAt: '23:00',
    priceRange: 3,
    crowdCapacity: 60,
    googleRating: 4.0,
    vibeTags: ['poolside', 'relaxed', 'harbour-view'],
    genreTags: ['lounge', 'chill'],
  },
  {
    name: 'The Library',
    slug: 'the-library-colombo',
    category: 'speakeasy',
    description: 'Hidden cocktail bar behind a bookshelf door with literary-themed drinks and low-lit ambiance.',
    area: 'cinnamon_gardens',
    country: 'LK',
    address: 'Park Street Mews, 50/1 Park St, Colombo 02',
    lat: 6.9140,
    lng: 79.8555,
    instagramHandle: 'thelibrarycmb',
    barClosesAt: '00:00',
    priceRange: 3,
    crowdCapacity: 40,
    googleRating: 4.4,
    vibeTags: ['hidden', 'literary', 'intimate'],
    genreTags: ['jazz', 'ambient'],
  },
  {
    name: 'Love Bar',
    slug: 'love-bar-colombo',
    category: 'bar',
    description: 'Trendy cocktail bar on Duplication Road known for themed nights and inventive syrups.',
    area: 'bambalapitiya',
    country: 'LK',
    address: '17 Duplication Rd, Colombo 04',
    lat: 6.8915,
    lng: 79.8570,
    instagramHandle: 'lovebarcolombo',
    barClosesAt: '01:00',
    priceRange: 2,
    crowdCapacity: 65,
    googleRating: 4.1,
    vibeTags: ['trendy', 'themed-nights', 'creative'],
    genreTags: ['pop', 'house', 'dancehall'],
  },
  {
    name: 'Breeze Bar',
    slug: 'breeze-bar-galle-face',
    category: 'rooftop',
    description: 'Open-air terrace bar at Galle Face Hotel with Indian Ocean breezes and colonial-era charm.',
    area: 'fort',
    country: 'LK',
    address: 'Galle Face Hotel, 2 Kollupitiya Rd, Colombo 03',
    lat: 6.9200,
    lng: 79.8450,
    instagramHandle: 'galleface_breeze',
    barClosesAt: '00:00',
    priceRange: 3,
    crowdCapacity: 80,
    googleRating: 4.2,
    vibeTags: ['colonial', 'ocean-view', 'elegant'],
    genreTags: ['jazz', 'lounge'],
  },
  {
    name: 'Club Mojo',
    slug: 'club-mojo-colombo',
    category: 'club',
    description: 'High-energy dance club in Kollupitiya with a powerful sound system and themed party nights.',
    area: 'kollupitiya',
    country: 'LK',
    address: '22 De Fonseka Rd, Colombo 05',
    lat: 6.9000,
    lng: 79.8585,
    instagramHandle: 'clubmojocmb',
    barClosesAt: '03:00',
    priceRange: 2,
    crowdCapacity: 250,
    googleRating: 3.7,
    vibeTags: ['high-energy', 'late-night', 'party'],
    genreTags: ['EDM', 'hip-hop', 'dancehall'],
  },
  {
    name: 'Sidecar Lounge',
    slug: 'sidecar-lounge-colombo',
    category: 'lounge',
    description: 'Motorcycle-themed cocktail lounge in Bambalapitiya with vintage decor and whisky selection.',
    area: 'bambalapitiya',
    country: 'LK',
    address: '28 Melbourne Ave, Colombo 04',
    lat: 6.8935,
    lng: 79.8575,
    instagramHandle: 'sidecarloungelk',
    barClosesAt: '01:00',
    priceRange: 2,
    crowdCapacity: 55,
    googleRating: 4.0,
    vibeTags: ['vintage', 'whisky', 'themed'],
    genreTags: ['rock', 'blues', 'indie'],
  },
  {
    name: 'Mount Beach Club',
    slug: 'mount-beach-club',
    category: 'club',
    description: 'Open-air beach club in Mount Lavinia with full-moon parties and international guest DJs.',
    area: 'mount_lavinia',
    country: 'LK',
    address: '55 College Ave, Mount Lavinia',
    lat: 6.8375,
    lng: 79.8640,
    instagramHandle: 'mountbeachclub',
    barClosesAt: '02:00',
    priceRange: 2,
    crowdCapacity: 400,
    googleRating: 3.8,
    vibeTags: ['beachfront', 'full-moon', 'open-air'],
    genreTags: ['techno', 'house', 'EDM'],
  },
  {
    name: 'Ceylon Wine & Spirits',
    slug: 'ceylon-wine-spirits',
    category: 'bar',
    description: 'Upscale wine bar and tasting room in Cinnamon Gardens with a curated New World wine list.',
    area: 'cinnamon_gardens',
    country: 'LK',
    address: '10 Maitland Crescent, Colombo 07',
    lat: 6.9020,
    lng: 79.8620,
    instagramHandle: 'ceylonwinespirits',
    barClosesAt: '00:00',
    priceRange: 3,
    crowdCapacity: 50,
    googleRating: 4.2,
    vibeTags: ['wine', 'upscale', 'date-night'],
    genreTags: ['jazz', 'classical'],
  },
];

async function main() {
  console.log('Seeding venues...');
  for (const v of venues) {
    await prisma.venue.upsert({
      where: { slug: v.slug },
      update: v,
      create: v,
    });
  }
  console.log(`Seeded ${venues.length} venues (${venues.filter(v => v.country === 'MY').length} MY, ${venues.filter(v => v.country === 'LK').length} LK)`);
}

main()
  .then(() => prisma.$disconnect())
  .catch((e) => {
    console.error(e);
    prisma.$disconnect();
    process.exit(1);
  });
