import { PrismaClient } from '../src/prisma/generated';

const prisma = new PrismaClient();

const venues = [
  // ── Malaysia — Kuala Lumpur ──
  {
    name: 'Zouk KL',
    slug: 'zouk-kl',
    category: 'club',
    description: 'Iconic superclub spanning multiple rooms with world-class DJs and immersive production.',
    area: 'trec',
    country: 'MY',
    address: 'TREC, 436 Jalan Tun Razak, 50400 Kuala Lumpur',
    lat: 3.1555,
    lng: 101.7163,
    instagramHandle: 'zoukkl',
    barClosesAt: '03:00',
    priceRange: 3,
    crowdCapacity: 1500,
    googleRating: 4.0,
    vibeTags: ['energetic', 'premium', 'late-night'],
    genreTags: ['EDM', 'house', 'hip-hop'],
  },
  {
    name: 'Heli Lounge Bar',
    slug: 'heli-lounge-bar',
    category: 'rooftop',
    description: 'Open-air rooftop bar on a helipad with panoramic KL skyline views.',
    area: 'bukit_bintang',
    country: 'MY',
    address: '34th Floor, Menara KH, Jalan Sultan Ismail, 50250 KL',
    lat: 3.1490,
    lng: 101.7100,
    instagramHandle: 'heliloungebar',
    barClosesAt: '01:00',
    priceRange: 3,
    crowdCapacity: 200,
    googleRating: 4.2,
    vibeTags: ['scenic', 'chill', 'instagrammable'],
    genreTags: ['lounge', 'deep house'],
  },
  {
    name: 'PS150',
    slug: 'ps150',
    category: 'speakeasy',
    description: 'Award-winning speakeasy hidden behind a toy shop facade in Chinatown.',
    area: 'chinatown',
    country: 'MY',
    address: '150 Jalan Petaling, 50000 Kuala Lumpur',
    lat: 3.1438,
    lng: 101.6960,
    instagramHandle: 'ps150bar',
    barClosesAt: '01:00',
    priceRange: 3,
    crowdCapacity: 80,
    googleRating: 4.5,
    vibeTags: ['intimate', 'craft-cocktails', 'hidden'],
    genreTags: ['jazz', 'ambient'],
  },
  {
    name: 'Coley Cocktail Bar',
    slug: 'coley-cocktail-bar',
    category: 'bar',
    description: 'Top-ranked cocktail bar known for creative Malaysian-inspired drinks.',
    area: 'bangsar',
    country: 'MY',
    address: '6, Jalan Kemuja, Bangsar, 59000 KL',
    lat: 3.1300,
    lng: 101.6715,
    instagramHandle: 'coleycocktailbar',
    barClosesAt: '00:00',
    priceRange: 3,
    crowdCapacity: 60,
    googleRating: 4.6,
    vibeTags: ['craft-cocktails', 'cozy', 'date-night'],
    genreTags: ['jazz', 'soul'],
  },
  {
    name: 'Havana Bar & Grill',
    slug: 'havana-bar-grill',
    category: 'bar',
    description: 'Lively Latin-themed bar on Changkat with live music and mojitos.',
    area: 'changkat',
    country: 'MY',
    address: '2 Changkat Bukit Bintang, 50200 KL',
    lat: 3.1465,
    lng: 101.7095,
    instagramHandle: 'havanamalaysia',
    barClosesAt: '02:00',
    priceRange: 2,
    crowdCapacity: 120,
    googleRating: 4.1,
    vibeTags: ['lively', 'latin', 'live-music'],
    genreTags: ['latin', 'reggaeton', 'salsa'],
  },
  {
    name: 'Elysium KL',
    slug: 'elysium-kl',
    category: 'club',
    description: 'Premium nightclub in TREC with themed rooms and international DJ lineups.',
    area: 'trec',
    country: 'MY',
    address: 'TREC, 438 Jalan Tun Razak, 50400 KL',
    lat: 3.1557,
    lng: 101.7165,
    instagramHandle: 'elysiumkl',
    barClosesAt: '03:00',
    priceRange: 4,
    crowdCapacity: 800,
    googleRating: 3.8,
    vibeTags: ['vip', 'premium', 'bottle-service'],
    genreTags: ['EDM', 'techno', 'commercial'],
  },
  {
    name: 'View Rooftop Bar',
    slug: 'view-rooftop-bar',
    category: 'rooftop',
    description: 'Stylish rooftop with infinity pool views overlooking the Petronas Towers.',
    area: 'klcc',
    country: 'MY',
    address: 'Level 39, GTower, Jalan Tun Razak, 50400 KL',
    lat: 3.1580,
    lng: 101.7210,
    instagramHandle: 'viewrooftopbar',
    barClosesAt: '01:00',
    priceRange: 4,
    crowdCapacity: 150,
    googleRating: 4.3,
    vibeTags: ['skyline', 'premium', 'sunset'],
    genreTags: ['lounge', 'house'],
  },
  {
    name: 'The Whisky Bar',
    slug: 'the-whisky-bar',
    category: 'bar',
    description: 'Cozy whisky-focused bar in Changkat with over 300 labels.',
    area: 'changkat',
    country: 'MY',
    address: '46 Changkat Bukit Bintang, 50200 KL',
    lat: 3.1470,
    lng: 101.7098,
    instagramHandle: 'thewhiskybar_kl',
    barClosesAt: '01:00',
    priceRange: 3,
    crowdCapacity: 50,
    googleRating: 4.4,
    vibeTags: ['intimate', 'whisky', 'sophisticated'],
    genreTags: ['jazz', 'blues'],
  },
  {
    name: 'Jungle Bird',
    slug: 'jungle-bird',
    category: 'bar',
    description: 'Tiki-inspired craft cocktail bar with tropical drinks and quirky decor.',
    area: 'damansara',
    country: 'MY',
    address: 'Plaza Damansara, Jalan Medan Setia 1, 50490 KL',
    lat: 3.1385,
    lng: 101.6580,
    instagramHandle: 'junglebirdkl',
    barClosesAt: '00:00',
    priceRange: 2,
    crowdCapacity: 45,
    googleRating: 4.5,
    vibeTags: ['tiki', 'creative', 'funky'],
    genreTags: ['reggae', 'funk'],
  },
  {
    name: 'Fuego at Troika',
    slug: 'fuego-at-troika',
    category: 'lounge',
    description: 'Upscale South American lounge with live DJs and stunning KLCC views.',
    area: 'klcc',
    country: 'MY',
    address: 'Level 23A, Tower B, The Troika, Persiaran KLCC, 50450 KL',
    lat: 3.1575,
    lng: 101.7195,
    instagramHandle: 'fuegokl',
    barClosesAt: '02:00',
    priceRange: 4,
    crowdCapacity: 200,
    googleRating: 4.2,
    vibeTags: ['upscale', 'views', 'latin'],
    genreTags: ['latin', 'house', 'commercial'],
  },

  // ── Sri Lanka — Colombo ──
  {
    name: 'Sky Lounge Colombo',
    slug: 'sky-lounge-colombo',
    category: 'rooftop',
    description: 'Colombo\'s premier rooftop bar atop Kingsbury Hotel with ocean views.',
    area: 'fort',
    country: 'LK',
    address: 'The Kingsbury, 48 Janadhipathi Mawatha, Colombo 01',
    lat: 6.9344,
    lng: 79.8428,
    instagramHandle: 'kingsburycolombo',
    barClosesAt: '01:00',
    priceRange: 4,
    crowdCapacity: 120,
    googleRating: 4.1,
    vibeTags: ['ocean-view', 'premium', 'sunset'],
    genreTags: ['lounge', 'deep house'],
  },
  {
    name: 'ON14 Rooftop Bar',
    slug: 'on14-rooftop-bar',
    category: 'rooftop',
    description: 'Award-winning rooftop lounge on the 14th floor with craft cocktails and city panorama.',
    area: 'kollupitiya',
    country: 'LK',
    address: 'OZO Colombo, 36 Kollupitiya Rd, Colombo 03',
    lat: 6.9110,
    lng: 79.8498,
    instagramHandle: 'on14rooftop',
    barClosesAt: '00:00',
    priceRange: 3,
    crowdCapacity: 80,
    googleRating: 4.3,
    vibeTags: ['craft-cocktails', 'scenic', 'lounge'],
    genreTags: ['house', 'chill'],
  },
  {
    name: 'The Honey Beach Club',
    slug: 'the-honey-beach-club',
    category: 'club',
    description: 'Beachfront party venue in Mount Lavinia with weekend DJ nights and pool parties.',
    area: 'mount_lavinia',
    country: 'LK',
    address: 'Marine Drive, Mount Lavinia',
    lat: 6.8385,
    lng: 79.8645,
    instagramHandle: 'honeybeachclub',
    barClosesAt: '02:00',
    priceRange: 2,
    crowdCapacity: 300,
    googleRating: 3.9,
    vibeTags: ['beachfront', 'pool-party', 'weekend'],
    genreTags: ['EDM', 'commercial', 'reggaeton'],
  },
  {
    name: 'Rhythm & Blues',
    slug: 'rhythm-and-blues',
    category: 'bar',
    description: 'Colombo\'s go-to live music bar with nightly bands and a loyal crowd.',
    area: 'kollupitiya',
    country: 'LK',
    address: 'Daytona Bldg, 25 Chatham St, Colombo 03',
    lat: 6.9125,
    lng: 79.8510,
    instagramHandle: 'rnbcolombo',
    barClosesAt: '01:00',
    priceRange: 2,
    crowdCapacity: 100,
    googleRating: 4.2,
    vibeTags: ['live-music', 'lively', 'classic'],
    genreTags: ['rock', 'blues', 'covers'],
  },
  {
    name: 'Curve Bar',
    slug: 'curve-bar',
    category: 'lounge',
    description: 'Chic cocktail lounge inside Colombo Courtyard with art-deco interiors.',
    area: 'cinnamon_gardens',
    country: 'LK',
    address: '32 Alfred House Ave, Colombo 03',
    lat: 6.9065,
    lng: 79.8575,
    instagramHandle: 'curvebarcolombo',
    barClosesAt: '00:00',
    priceRange: 3,
    crowdCapacity: 60,
    googleRating: 4.0,
    vibeTags: ['chic', 'art-deco', 'date-night'],
    genreTags: ['lounge', 'jazz'],
  },
];

async function main() {
  console.log('Seeding venues...');
  for (const v of venues) {
    await prisma.venue.upsert({
      where: { slug: v.slug },
      update: v,
      create: v,
    });
  }
  console.log(`Seeded ${venues.length} venues (${venues.filter(v => v.country === 'MY').length} MY, ${venues.filter(v => v.country === 'LK').length} LK)`);
}

main()
  .then(() => prisma.$disconnect())
  .catch((e) => {
    console.error(e);
    prisma.$disconnect();
    process.exit(1);
  });
